AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Layout/LineLength:
  Max: 120

Lint/EmptyClass:
  AllowComments: true

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 11

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Security/Open:
  Enabled: false
